### ISSUE TITLE
几个BUG，希望处理下。。

### ISSUE THREAD

**Issue by hulang** [mHalo/beautiy-kindeditor#2]
1.ke-icon-quote  鼠标经过是：undefined
2.编辑器内有图片，图片下面有很多文件的时候，再对图片，右键编辑的时候，会回弹到上面去。。能不能不回弹，哪个位子右键的就在那里，`autoHeightMode: false`  这个参数设置成false测试。。..
测试代码如下：
```html
<p>
	<img src="/attached/image/20230215/75d077345d732dabbe239dff423694f9b22d0d61.png" alt="" /> 
</p>
<p>
	<br />
</p>
<p>
	<br />
</p>
<p>
	<br />
</p>
<p>
	<br />
</p>
<p>
	<br />
</p>
<p>
	<br />
</p>
<p>
	的撒发生发大师傅
</p>
<p>
	啊的首发式发生
</p>
<p>
	阿斯顿发顺丰打赏啊大师傅大势发
</p>
<p>
	阿斯顿发大水发
</p>
```

**Comment by hulang** [comment]
还有：publish文件夹下面没有：dist，直接下载你的全部项目，不行，必须去npm。用命令弄。你能不能：一劳永逸，直接弄到你项目里面。。。这样方便大家，下载后。运行demo。。可以直接看效果。。。。

**Comment by hulang** [comment]
不会玩：pulls。。。上传一个：emoji插件。。。希望作者整合到里面去。。。
[emoji.zip](https://github.com/mHalo/mhalo.kindeditor/files/10741387/emoji.zip)

**Comment by hulang** [comment]
emoji插件纯浏览器支持的。。。
![微信截图_20230215172155](https://user-images.githubusercontent.com/4961831/218986698-d42fc941-eae2-4623-b0e3-0f70180bfe52.png)

**Comment by mHalo** [comment]
好的，**1.ke-icon-quote 鼠标经过是：undefined** 这个已经修复过；dist文件夹也已经包含在版本库中。其它几个部分接下来会做下调整和完善。

**Comment by mHalo** [comment]
> 2.编辑器内有图片，图片下面有很多文件的时候，再对图片，右键编辑的时候，会回弹到上面去。。能不能不回弹，哪个位子右键的就在那里，autoHeightMode: false 这个参数设置成false测试。。..

这个部分请参考：  https://github.com/kindsoft/kindeditor/issues/54 中所提的问题，在解决此问题时，编辑器增加了滚动到当前图片的相关代码
@hulang

**Comment by hulang** [comment]
@mHalo 不是这个意思，我的意思是上面的那段代码，比如图片在最上面，你现在正在下面输入文字，如果图片上传错了。鼠标往上看到图片后，鼠标直接对图片，右键编辑，这个时候，会自动往上，到图片的位子，这个是错误的，应该就是当前位子。而不是自动往上。。这个BUG存在很久了。。官方的issues好几个用户反馈了。

**Comment by hulang** [comment]
视音频插件里面是4个英文，也可以加到语言包，不就是：预加载，自动播放，控制，循环   吗？

**Comment by hulang** [comment]
@hulang 当富文本内容较多的时候，修改字体大小、字体颜色 等 ，内容定位出现问题。。希望保存不变。。
![动画](https://user-images.githubusercontent.com/4961831/219527443-42a2bf89-9a06-496a-a568-7ebafcc60cc5.gif)

**Comment by hulang** [comment]
git图片700多kb显示太慢，就看这个：https://github.com/kindsoft/kindeditor/issues/303

**Comment by mHalo** [comment]
@hulang  v4.4.1 已更新，更新日志如下  
1. 修复quote插件工具栏中hover提示undefined
2. 源码增加dist文件夹（/publish/dist），可直接下载使用
3. 将[kindsoft/kindeditor#54](https://github.com/kindsoft/kindeditor/issues/54)中bugfix的处理方式扩展为可配置，默认情况下，设置样式或上传编辑图片时，编辑器不再自动滚动至将编辑内容所在的位置。如需保持原逻辑，可通过一下方式开启：
```
K.create('#editor', {
    scrollToEditingTarget: true,
});
```
4. 增加emoji插件，**K.Tools.Normal** 配置中已默认包含此插件。emoji信息可按照以下方案进行配置：
```
K.create('#editor', {
    emojiConfig:function(emojis, page){
        page.cols = 12
    },
});
```
5. 更新部分样式

**Comment by hulang** [comment]
@mHalo 非常不错。。。
我想问，如何扩展：`http://[at.alicdn.com/t/c/font_1491367_8kig7bk8pn.css](http://at.alicdn.com/t/c/font_1491367_8kig7bk8pn.css)`
我需要几个图标：微信，支付宝，QQ，手机，二维码。。怎么扩展呢。。。还是我在：default.css里面扩展。。。

**Comment by hulang** [comment]
@mHalo 
preload = 预载 autoplay = 自动播放
controls = 控制  loop = 循环

这个作者你也做到：lang里面去啊。。统一下。。

**Comment by hulang** [comment]
@mHalo 默认的工具栏里面的地图是：google地图。。点击没有发现：plugins/map/map.js。。。作者你默认加载：百度地图就行了。
百度地图文件里面的http://和https://  换成： //比较好。。。

**Comment by mHalo** [comment]
> @mHalo 默认的工具栏里面的地图是：google地图。。点击没有发现：plugins/map/map.js。。。作者你默认加载：百度地图就行了。 百度地图文件里面的[http://和https://](http://%E5%92%8Chttps://) 换成： //比较好。。。

好的，最近会做下优化，麻烦下次有反馈bug的话提新的issue哈

**Comment by hulang** [comment]
@mHalo 我是怕太麻烦了，所以直接一个：issue
