### ISSUE TITLE
图片宽度和高度能否加个参数控制？

### ISSUE THREAD

**Issue by hulang** [mHalo/beautiy-kindeditor#3]
比如，现在的demo页面中的那张图片。
你点击右键，进行图片属性，就会自动获取图片的高度和宽度，我不想设置高度和宽度，
进行删除，然后出现的现象是你删除高度和宽度就互相在玩一样，你删除：宽度，点击高度的设置，就会变成：NaN，
那反过来就是：你删除：高度，点击宽度的设置，就会变成：NaN....查看html代码，实际没有设置图片的高宽。。
能否加个参数控制，不自动获取高宽，或者图片界面，可以不显示：高宽？

**Comment by hulang** [comment]
上传后返回的json无法兼容，我使用官方的可以。。。比如：
[http://kindeditor.net/docs/upload.html](http://kindeditor.net/docs/upload.html)
返回格式(JSON)
`//成功时
{
        "error" : 0,
        "url" : "http://www.example.com/path/to/file.ext"
}
//失败时
{
        "error" : 1,
        "message" : "错误信息"
}`

你的好像是：
`//成功时
{
        "error" : 0,
        "url" : "http://www.example.com/path/to/file.ext",
        "data" : "获取的是这个里面的。。。。",
}
//失败时
{
        "error" : 1,
        "message" : "错误信息",
        "data" : "获取的是这个里面的。。。。",
}`

也就是说。你写的好像是获取返回json里面data节点的。。。不知道是我理解错了。还是？
@mHalo

**Comment by mHalo** [comment]
> 上传后返回的json无法兼容，我使用官方的可以。。。比如： http://kindeditor.net/docs/upload.html 返回格式(JSON) `//成功时 { "error" : 0, "url" : "http://www.example.com/path/to/file.ext" } //失败时 { "error" : 1, "message" : "错误信息" }`
> 
> 你的好像是： `//成功时 { "error" : 0, "url" : "http://www.example.com/path/to/file.ext", "data" : "获取的是这个里面的。。。。", } //失败时 { "error" : 1, "message" : "错误信息", "data" : "获取的是这个里面的。。。。", }`
> 
> 也就是说。你写的好像是获取返回json里面data节点的。。。不知道是我理解错了。还是？ @mHalo

@hulang  现已将上传时的返回的数据格式恢复至kindeditor默认格式，并新增了[**uploadResponseFilter**]参数来对返回结果做处理。使用方式可查看[更新日志](https://github.com/mHalo/mhalo.kindeditor/blob/main/UPDATE.md)。

**Comment by hulang** [comment]
@mHalo 好的。
